version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: alex
      POSTGRES_PASSWORD: alex77777
      POSTGRES_DB: my_db

  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    links:
      - db
